{{- range $index, $cert := .Values.global.certs }}
{{- $data := pluck $cert.name $.Values.data | first }}
{{- $tls := pluck $.Values.global.env $data | first }}
---
apiVersion: v1
data:
  tls.crt: {{ $tls.crt }}
  tls.key: {{ $tls.key }}
kind: Secret
metadata:
  name: {{ $.Chart.Name }}-{{ $cert.name }}
  labels:
    secret-copier.deckhouse.io/enabled: ''
type: kubernetes.io/tls
{{- end }}